Vagrant.configure("2") do |config|
    config.vm.box = "centos/7"

    config.vm.provider :virtualbox do |virtualbox, override|
      virtualbox.memory = 2048
      override.vm.box_download_checksum_type = "sha256"
      override.vm.box_download_checksum = "7e83943defcb5c4e9bebbe4184cce4585c82805a15e936b01b1e893b63dee2c5"
      override.vm.box_url = "https://cloud.centos.org/centos/7/vagrant/x86_64/images/CentOS-7-x86_64-Vagrant-2004_01.VirtualBox.box"
    end
  end
