---
- name: Instala y create el archivo de configuracion para containerD
  hosts: kubernetes
  become: true
  gather_facts: false

  tasks:
    - name: Correr las actualizaciones
      ansible.builtin.apt:
        upgrade: dist
        update_cache: yes
    - name: Verificar port ca-certificates y curl
      ansible.builtin.apt:
        name:
          ca-certificates
          curl
    - name: Obtener la llave GPG oficial de Docker
      ansible.builtin.shell: |
        sudo mkdir -m 755 -p /etc/apt/keyrings
        sudo curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc
        sudo chmod a+r /etc/apt/keyrings/docker.asc

    - name: Crear el archivo para el repositorio de Dockers
      ansible.builtin.shell: |

    - name: Instala containerd.io
      ansible.builtin.apt:
        name:
          - containerd.io

    - name: Crea el directorio containerd
      ansible.builtin.shell: |
        sudo mkdir -p /etc/containerd

    - name: Crea un archivo general para containerd config toml
      ansible.builtin.shell: |
        sudo containerd config default | sudo tee /etc/containerd/config.toml 