---
- name: Instala los kube* para los servidores de Kubernetes
  hosts: kubernetes
  become: true
  gather_facts: false
  
  tasks:
    - name: Corre las actualizaciones
      ansible.builtin.apt:
        upgrade: dist
        update_cache: yes
        
    - name: Instala los siguientes paquetes kubelet, kubeadmin, y kubectl
      ansible.builtin.apt:
        name:
          - kubeadm
          - kubectl
          - kubelet
    
    - name: Marcar los paquetes kube* con hold
      ansible.builtin.shell:
        sudo apt-mark hold kubectl kubeadm kubelet  