---
- name: Verify /etc/apt/keyrings exists and then download the public signing key for the Kubernetes package repositories
  hosts: kubernetes
  become: true
  gather_facts: false
  vars:
    target_directory: "/etc/apt/keyrings"


  tasks:
    - name: Verify "{{ target_directory }}" exists
      ansible.builtin.stat:
          path: "{{ target_directory }}"
      register: dir_check
    - name: Download the public signing key for the Kubernetes package repositories
      ansible.builtin.shell: |
        curl -fsSL https://pkgs.k8s.io/core:/stable:/v1.36/deb/Release.key | sudo gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg
      when: dir_check.stat.exists and dir_check.stat.isdir  