---
- hosts: hypervisors
  tasks:
    - name: Install basic packages
      ansible.builtin.package:
        name:
          - tree
          - parted
          - vim
          - git
          - epel-release
        state: latest