---
- hosts: Local
  tasks:
    - name: Install basic packages
      ignore_unreachable: yes
      ansible.builtin.package:
        name:
          - tree
          - parted
          - vim
          - git
          - epel-release
          - ansible
          - terminator
          - ipcalc
          - aide
        state: latest