---
- name: Open-SCAP
  hosts: openscap
  become: true
  vars:
    scap:
      - scap-security-guide
      - openscap-scanner

  tasks:
    
    - name: Install "{{ scap }}"
      dnf:
        name: "{{ scap }}"
        state: absent
      loop: "{{ scap }}"